export type RouteID =
	'ROOT' |
	'BATTLE_CONFIG' |
	'BATTLE' |
	'BATTLE_SUMMARY' |
	'PARTY_LIST' |
	'PARTY_EDIT' |
	'PARTY_CREATE' |
	'CHARACTER_LIST' |
	'CHARACTER_EDIT' |
	'CHARACTER_CREATE';
