import { ISkillData } from 'engine/skill';

type IPartialSkillList<T extends MagicSkillID> = {
	[id in T]: ISkillData;
};

export type MagicSkillID =
	'NONE' |
	'PSYCHOKINESIS_KINETIC_STRIKE' | 'PSYCHOKINESIS_FORGET' | 'PSYCHOKINESIS_PSYCHODOME' |
	'WHITE_MAGIC_HEAL' | 'WHITE_MAGIC_REMEDY' | 'WHITE_MAGIC_REGENERATE' | 'WHITE_MAGIC_GROUP_HEAL' | 'WHITE_MAGIC_HOLY_AURA' | 'WHITE_MAGIC_REVIVE' |
	'BLACK_MAGIC_DARK_AURA' |
	'FIRE_MAGIC_FIREBALL' | 'FIRE_MAGIC_BURN' | 'FIRE_MAGIC_FIRESTORM' | 'FIRE_MAGIC_FIRE_AURA' |
	'WATER_MAGIC_SPLASH' | 'WATER_MAGIC_SILENCE' | 'WATER_MAGIC_FLOOD' | 'WATER_MAGIC_WATER_AURA' |
	'WIND_MAGIC_AIR_BLAST' | 'WIND_MAGIC_JET_STREAM' | 'WIND_MAGIC_TORNADO' | 'WIND_MAGIC_WIND_AURA' |
	'EARTH_MAGIC_BOULDER' | 'EARTH_MAGIC_EARTH_SPIKE' | 'EARTH_MAGIC_EARTHQUAKE' | 'EARTH_MAGIC_STONE_SKIN' |
	'ICE_MAGIC_ICE_SPEAR' | 'ICE_MAGIC_FREEZE' | 'ICE_MAGIC_BLIZZARD' | 'ICE_MAGIC_FROST_AURA' |
	'THUNDER_MAGIC_THUNDERBOLT' | 'THUNDER_MAGIC_SHOCK' | 'THUNDER_MAGIC_THUNDERSTORM' | 'THUNDER_MAGIC_THUNDER_AURA';

export type IWhiteMagicSkillList = IPartialSkillList<
	'WHITE_MAGIC_HEAL' | 'WHITE_MAGIC_REMEDY' | 'WHITE_MAGIC_REGENERATE' | 'WHITE_MAGIC_GROUP_HEAL' | 'WHITE_MAGIC_HOLY_AURA' | 'WHITE_MAGIC_REVIVE'
>;

export type IBlackMagicSkillList = IPartialSkillList<
	'BLACK_MAGIC_DARK_AURA'
>;

export type IFireMagicSkillList = IPartialSkillList<
	'FIRE_MAGIC_FIREBALL' | 'FIRE_MAGIC_BURN' | 'FIRE_MAGIC_FIRESTORM' | 'FIRE_MAGIC_FIRE_AURA'
>;

export type IWaterMagicSkillList = IPartialSkillList<
	'WATER_MAGIC_SPLASH' | 'WATER_MAGIC_SILENCE' | 'WATER_MAGIC_FLOOD' | 'WATER_MAGIC_WATER_AURA'
>;

export type IWindMagicSkillList = IPartialSkillList<
	'WIND_MAGIC_AIR_BLAST' | 'WIND_MAGIC_JET_STREAM' | 'WIND_MAGIC_TORNADO' | 'WIND_MAGIC_WIND_AURA'
>;

export type IEarthMagicSkillList = IPartialSkillList<
	'EARTH_MAGIC_BOULDER' | 'EARTH_MAGIC_EARTH_SPIKE' | 'EARTH_MAGIC_EARTHQUAKE' | 'EARTH_MAGIC_STONE_SKIN'
>;

export type IIceMagicSkillList = IPartialSkillList<
	'ICE_MAGIC_ICE_SPEAR' | 'ICE_MAGIC_FREEZE' | 'ICE_MAGIC_BLIZZARD' | 'ICE_MAGIC_FROST_AURA'
>;

export type IThunderMagicSkillList = IPartialSkillList<
	'THUNDER_MAGIC_THUNDERBOLT' | 'THUNDER_MAGIC_SHOCK' | 'THUNDER_MAGIC_THUNDERSTORM' | 'THUNDER_MAGIC_THUNDER_AURA'
>;

export type IPsychokinesisSkillList = IPartialSkillList<
	'PSYCHOKINESIS_KINETIC_STRIKE' | 'PSYCHOKINESIS_FORGET' | 'PSYCHOKINESIS_PSYCHODOME'
>;
