export enum JobSkillID {
	NONE = 'NONE',
	BERSERKING_BERSERK = 'BERSERKING_BERSERK',
	KNIGHTHOOD_ULTIMATE_DEFENSE = 'KNIGHTHOOD_ULTIMATE_DEFENSE',
	SUPREMACY_NONE = 'SUPREMACY_NONE',
	PROGRAM_NONE = 'PROGRAM_NONE',
	WEAPON_MASTERY_NONE = 'WEAPON_MASTERY_NONE',
	COMBAT_NONE = 'COMBAT_NONE',
	TRACKING_NONE = 'TRACKING_NONE',
	LYCANTHROPY_NONE = 'LYCANTHROPY_NONE',
	MYSTIC_ART_NONE = 'MYSTIC_ART_NONE',
	DIVINITY_NONE = 'DIVINITY_NONE',
	CORRUPTION_NONE = 'CORRUPTION_NONE',

	FLAMEBLADE_FLAMESTRIKE = 'FLAMEBLADE_FLAMESTRIKE',
	FLAMEBLADE_FIREBALL = 'FLAMEBLADE_FIREBALL',

	WATERBLADE_WATERSTRIKE = 'WATERBLADE_WATERSTRIKE',
	WATERBLADE_SPLASH = 'WATERBLADE_WATERSPLASH',

	AIRBLADE_WINDSTRIKE = 'AIRBLADE_WINDSTRIKE',
	AIRBLADE_AIR_BLAST = 'AIRBLADE_AIR_BLAST',

	STONEBLADE_EARTHSTRIKE = 'STONEBLADE_EARTHSTRIKE',
	STONEBLADE_BOULDER = 'STONEBLADE_BOULDER',

	FROSTBLADE_FROSTSTRIKE = 'FROSTBLADE_FROSTSTRIKE',
	FROSTBLADE_FROSTSPEAR = 'FROSTBLADE_FROSTSPEAR',

	THUNDERBLADE_THUNDERSTRIKE = 'THUNDERBLADE_THUNDERSTRIKE',
	THUNDERBLADE_THUNDREBOLT = 'THUNDERBLADE_THUNDREBOLT',

	BLITZ_NONE = 'BLITZ_NONE',
	AIM_NONE = 'AIM_NONE',
	PERFORMANCE_NONE = 'PERFORMANCE_NONE',
	VAMPIRISM_NONE = 'VAMPIRISM_NONE',
	ILLUSION_NONE = 'ILLUSION_INVISIBILITY',
	MARTIAL_ARTS_NONE = 'MARTIAL_ARTS_NONE',
	ASSASSINATION_NONE = 'ASSASSINATION_NONE',
	ALCHEMY_NONE = 'ALCHEMY_NONE',

	PSYCHOKINESIS_KINETIC_STRIKE = 'PSYCHOKINESIS_KINETIC_STRIKE',
	PSYCHOKINESIS_FORGET = 'PSYCHOKINESIS_FORGET',
	PSYCHOKINESIS_PSYCHODOME = 'PSYCHOKINESIS_PSYCHODOME',

	WHITE_MAGIC_HEAL = 'WHITE_MAGIC_HEAL',
	WHITE_MAGIC_REMEDY = 'WHITE_MAGIC_REMEDY',
	WHITE_MAGIC_REGENERATE = 'WHITE_MAGIC_REGENERATE',
	WHITE_MAGIC_GROUP_HEAL = 'WHITE_MAGIC_GROUP_HEAL',
	WHITE_MAGIC_HOLY_AURA = 'WHITE_MAGIC_HOLY_AURA',
	WHITE_MAGIC_REVIVE = 'WHITE_MAGIC_REVIVE',

	BLACK_MAGIC_DARK_AURA = 'BLACK_MAGIC_DARK_AURA',

	FIRE_MAGIC_FIREBALL = 'FIRE_MAGIC_FIREBALL',
	FIRE_MAGIC_BURN = 'FIRE_MAGIC_BURN',
	FIRE_MAGIC_FIRESTORM = 'FIRE_MAGIC_FIRESTORM',
	FIRE_MAGIC_FIRE_AURA = 'FIRE_MAGIC_FIRE_AURA',

	WATER_MAGIC_SPLASH = 'WATER_MAGIC_SPLASH',
	WATER_MAGIC_SILENCE = 'WATER_MAGIC_SILENCE',
	WATER_MAGIC_FLOOD = 'WATER_MAGIC_FLOOD',
	WATER_MAGIC_WATER_AURA = 'WATER_MAGIC_WATER_AURA',

	WIND_MAGIC_AIR_BLAST = 'WIND_MAGIC_AIR_BLAST',
	WIND_MAGIC_JET_STREAM = 'WIND_MAGIC_JET_STREAM',
	WIND_MAGIC_TORNADO = 'WIND_MAGIC_TORNADO',
	WIND_MAGIC_FLOAT = 'WIND_MAGIC_FLOAT',
	WIND_MAGIC_WIND_AURA = 'WIND_MAGIC_WIND_AURA',

	EARTH_MAGIC_BOULDER = 'EARTH_MAGIC_BOULDER',
	EARTH_MAGIC_EARTH_SPIKE = 'EARTH_MAGIC_EARTH_SPIKE',
	EARTH_MAGIC_EARTHQUAKE = 'EARTH_MAGIC_EARTHQUAKE',
	EARTH_MAGIC_STONE_SKIN = 'EARTH_MAGIC_STONE_SKIN',

	ICE_MAGIC_ICE_SPEAR = 'ICE_MAGIC_ICE_SPEAR',
	ICE_MAGIC_FREEZE = 'ICE_MAGIC_FREEZE',
	ICE_MAGIC_BLIZZARD = 'ICE_MAGIC_BLIZZARD',
	ICE_MAGIC_FROST_AURA = 'ICE_MAGIC_FROST_AURA',

	THUNDER_MAGIC_THUNDERBOLT = 'THUNDER_MAGIC_THUNDERBOLT',
	THUNDER_MAGIC_SHOCK = 'THUNDER_MAGIC_SHOCK',
	THUNDER_MAGIC_THUNDERSTORM = 'THUNDER_MAGIC_THUNDERSTORM',
	THUNDER_MAGIC_THUNDER_AURA = 'THUNDER_MAGIC_THUNDER_AURA'
}
