export enum SkillSetID {
	NONE = 'NONE',
	BERSERKING = 'BERSERKING',
	PROGRAM = 'PROGRAM',
	LYCANTROPHY = 'LYCANTROPHY',
	DANCING = 'DANCING',
	SINGING = 'SINGING',
	MAGIC_KINETIC = 'MAGIC_KINETIC',
	MAGIC_HOLY = 'MAGIC_HOLY',
	MAGIC_DARK = 'MAGIC_DARK',
	MAGIC_FIRE = 'MAGIC_FIRE',
	MAGIC_WATER = 'MAGIC_WATER',
	MAGIC_AIR = 'MAGIC_AIR',
	MAGIC_EARTH = 'MAGIC_EARTH'
}
