import { ISkill } from 'modules/skill';

type IPartialJobSkillList<T extends JobSkillID> = {
	[id in T]: ISkill;
};

export enum JobSkillID {
	NONE = 'NONE',
	BERSERKING_BERSERK = 'BERSERKING_BERSERK',
	KNIGHTHOOD_ULTIMATE_DEFENSE = 'KNIGHTHOOD_ULTIMATE_DEFENSE',
	SUPREMACY_NONE = 'SUPREMACY_NONE',
	PROGRAM_NONE = 'PROGRAM_NONE',
	WEAPON_MASTERY_NONE = 'WEAPON_MASTERY_NONE',
	COMBAT_NONE = 'COMBAT_NONE',
	TRACKING_NONE = 'TRACKING_NONE',
	LYCANTHROPY_NONE = 'LYCANTHROPY_NONE',
	MYSTIC_ART_NONE = 'MYSTIC_ART_NONE',
	DIVINITY_NONE = 'DIVINITY_NONE',
	CORRUPTION_NONE = 'CORRUPTION_NONE',

	FLAMEBLADE_FLAMESTRIKE = 'FLAMEBLADE_FLAMESTRIKE',
	FLAMEBLADE_FIREBALL = 'FLAMEBLADE_FIREBALL',

	WATERBLADE_WATERSTRIKE = 'WATERBLADE_WATERSTRIKE',
	WATERBLADE_SPLASH = 'WATERBLADE_WATERSPLASH',

	AIRBLADE_WINDSTRIKE = 'AIRBLADE_WINDSTRIKE',
	AIRBLADE_AIR_BLAST = 'AIRBLADE_AIR_BLAST',

	STONEBLADE_EARTHSTRIKE = 'STONEBLADE_EARTHSTRIKE',
	STONEBLADE_BOULDER = 'STONEBLADE_BOULDER',

	FROSTBLADE_FROSTSTRIKE = 'FROSTBLADE_FROSTSTRIKE',
	FROSTBLADE_FROSTSPEAR = 'FROSTBLADE_FROSTSPEAR',

	THUNDERBLADE_THUNDERSTRIKE = 'THUNDERBLADE_THUNDERSTRIKE',
	THUNDERBLADE_THUNDREBOLT = 'THUNDERBLADE_THUNDREBOLT',

	BLITZ_NONE = 'BLITZ_NONE',
	AIM_NONE = 'AIM_NONE',
	PERFORMANCE_NONE = 'PERFORMANCE_NONE',
	VAMPIRISM_NONE = 'VAMPIRISM_NONE',
	ILLUSION_NONE = 'ILLUSION_INVISIBILITY',
	MARTIAL_ARTS_NONE = 'MARTIAL_ARTS_NONE',
	ASSASSINATION_NONE = 'ASSASSINATION_NONE',
	ALCHEMY_NONE = 'ALCHEMY_NONE',

	PSYCHOKINESIS_KINETIC_STRIKE = 'PSYCHOKINESIS_KINETIC_STRIKE',
	PSYCHOKINESIS_FORGET = 'PSYCHOKINESIS_FORGET',
	PSYCHOKINESIS_PSYCHODOME = 'PSYCHOKINESIS_PSYCHODOME',

	WHITE_MAGIC_HEAL = 'WHITE_MAGIC_HEAL',
	WHITE_MAGIC_REMEDY = 'WHITE_MAGIC_REMEDY',
	WHITE_MAGIC_REGENERATE = 'WHITE_MAGIC_REGENERATE',
	WHITE_MAGIC_GROUP_HEAL = 'WHITE_MAGIC_GROUP_HEAL',
	WHITE_MAGIC_HOLY_AURA = 'WHITE_MAGIC_HOLY_AURA',
	WHITE_MAGIC_REVIVE = 'WHITE_MAGIC_REVIVE',

	BLACK_MAGIC_DARK_AURA = 'BLACK_MAGIC_DARK_AURA',

	FIRE_MAGIC_FIREBALL = 'FIRE_MAGIC_FIREBALL',
	FIRE_MAGIC_BURN = 'FIRE_MAGIC_BURN',
	FIRE_MAGIC_FIRESTORM = 'FIRE_MAGIC_FIRESTORM',
	FIRE_MAGIC_FIRE_AURA = 'FIRE_MAGIC_FIRE_AURA',

	WATER_MAGIC_SPLASH = 'WATER_MAGIC_SPLASH',
	WATER_MAGIC_SILENCE = 'WATER_MAGIC_SILENCE',
	WATER_MAGIC_FLOOD = 'WATER_MAGIC_FLOOD',
	WATER_MAGIC_WATER_AURA = 'WATER_MAGIC_WATER_AURA',

	WIND_MAGIC_AIR_BLAST = 'WIND_MAGIC_AIR_BLAST',
	WIND_MAGIC_JET_STREAM = 'WIND_MAGIC_JET_STREAM',
	WIND_MAGIC_TORNADO = 'WIND_MAGIC_TORNADO',
	WIND_MAGIC_FLOAT = 'WIND_MAGIC_FLOAT',
	WIND_MAGIC_WIND_AURA = 'WIND_MAGIC_WIND_AURA',

	EARTH_MAGIC_BOULDER = 'EARTH_MAGIC_BOULDER',
	EARTH_MAGIC_EARTH_SPIKE = 'EARTH_MAGIC_EARTH_SPIKE',
	EARTH_MAGIC_EARTHQUAKE = 'EARTH_MAGIC_EARTHQUAKE',
	EARTH_MAGIC_STONE_SKIN = 'EARTH_MAGIC_STONE_SKIN',

	ICE_MAGIC_ICE_SPEAR = 'ICE_MAGIC_ICE_SPEAR',
	ICE_MAGIC_FREEZE = 'ICE_MAGIC_FREEZE',
	ICE_MAGIC_BLIZZARD = 'ICE_MAGIC_BLIZZARD',
	ICE_MAGIC_FROST_AURA = 'ICE_MAGIC_FROST_AURA',

	THUNDER_MAGIC_THUNDERBOLT = 'THUNDER_MAGIC_THUNDERBOLT',
	THUNDER_MAGIC_SHOCK = 'THUNDER_MAGIC_SHOCK',
	THUNDER_MAGIC_THUNDERSTORM = 'THUNDER_MAGIC_THUNDERSTORM',
	THUNDER_MAGIC_THUNDER_AURA = 'THUNDER_MAGIC_THUNDER_AURA'
}

export type IAimJobSkillList = IPartialJobSkillList<JobSkillID.AIM_NONE>;
export type IAlchemyJobSkillList = IPartialJobSkillList<JobSkillID.ALCHEMY_NONE>;
export type IAssassinationJobSkillList = IPartialJobSkillList<JobSkillID.ASSASSINATION_NONE>;
export type IBerserkingJobSkillList = IPartialJobSkillList<JobSkillID.BERSERKING_BERSERK>;

export type IFlameBladeJobSkillList = IPartialJobSkillList<
	JobSkillID.FLAMEBLADE_FLAMESTRIKE|
	JobSkillID.FLAMEBLADE_FIREBALL
>;

export type IWaterBladeJobSkillList = IPartialJobSkillList<
	JobSkillID.WATERBLADE_WATERSTRIKE|
	JobSkillID.WATERBLADE_SPLASH
>;

export type IAirBladeJobSkillList = IPartialJobSkillList<
	JobSkillID.AIRBLADE_WINDSTRIKE|
	JobSkillID.AIRBLADE_AIR_BLAST
>;

export type IStoneBladeJobSkillList = IPartialJobSkillList<
	JobSkillID.STONEBLADE_EARTHSTRIKE|
	JobSkillID.STONEBLADE_BOULDER
>;

export type IFrostBladeJobSkillList = IPartialJobSkillList<
	JobSkillID.FROSTBLADE_FROSTSTRIKE|
	JobSkillID.FROSTBLADE_FROSTSPEAR
>;

export type IThunderBladeJobSkillList = IPartialJobSkillList<
	JobSkillID.THUNDERBLADE_THUNDERSTRIKE|
	JobSkillID.THUNDERBLADE_THUNDREBOLT
>;

export type IBlitzJobSkillList = IPartialJobSkillList<JobSkillID.BLITZ_NONE>;
export type ICombatJobSkillList = IPartialJobSkillList<JobSkillID.COMBAT_NONE>;
export type ICorruptionJobSkillList = IPartialJobSkillList<JobSkillID.CORRUPTION_NONE>;
export type IDivinityJobSkillList = IPartialJobSkillList<JobSkillID.DIVINITY_NONE>;
export type IIlusionJobSkillList = IPartialJobSkillList<JobSkillID.ILLUSION_NONE>;
export type IKnighthoodJobSkillList = IPartialJobSkillList<JobSkillID.KNIGHTHOOD_ULTIMATE_DEFENSE>;
export type ILycanthropyJobSkillList = IPartialJobSkillList<JobSkillID.LYCANTHROPY_NONE>;

export type IWhiteMagicJobSkillList = IPartialJobSkillList<
	JobSkillID.WHITE_MAGIC_HEAL|
	JobSkillID.WHITE_MAGIC_REMEDY|
	JobSkillID.WHITE_MAGIC_REGENERATE|
	JobSkillID.WHITE_MAGIC_GROUP_HEAL|
	JobSkillID.WHITE_MAGIC_HOLY_AURA|
	JobSkillID.WHITE_MAGIC_REVIVE
>;

export type IBlackMagicJobSkillList = IPartialJobSkillList<
	JobSkillID.BLACK_MAGIC_DARK_AURA
>;

export type IFireMagicJobSkillList = IPartialJobSkillList<
	JobSkillID.FIRE_MAGIC_FIREBALL|
	JobSkillID.FIRE_MAGIC_BURN|
	JobSkillID.FIRE_MAGIC_FIRESTORM|
	JobSkillID.FIRE_MAGIC_FIRE_AURA
>;

export type IWaterMagicJobSkillList = IPartialJobSkillList<
	JobSkillID.WATER_MAGIC_SPLASH|
	JobSkillID.WATER_MAGIC_SILENCE|
	JobSkillID.WATER_MAGIC_FLOOD|
	JobSkillID.WATER_MAGIC_WATER_AURA
>;

export type IWindMagicJobSkillList = IPartialJobSkillList<
	JobSkillID.WIND_MAGIC_AIR_BLAST|
	JobSkillID.WIND_MAGIC_JET_STREAM|
	JobSkillID.WIND_MAGIC_TORNADO|
	JobSkillID.WIND_MAGIC_FLOAT|
	JobSkillID.WIND_MAGIC_WIND_AURA
>;

export type IEarthMagicJobSkillList = IPartialJobSkillList<
	JobSkillID.EARTH_MAGIC_BOULDER|
	JobSkillID.EARTH_MAGIC_EARTH_SPIKE|
	JobSkillID.EARTH_MAGIC_EARTHQUAKE|
	JobSkillID.EARTH_MAGIC_STONE_SKIN
>;

export type IIceMagicJobSkillList = IPartialJobSkillList<
	JobSkillID.ICE_MAGIC_ICE_SPEAR|
	JobSkillID.ICE_MAGIC_FREEZE|
	JobSkillID.ICE_MAGIC_BLIZZARD|
	JobSkillID.ICE_MAGIC_FROST_AURA
>;

export type IThunderMagicJobSkillList = IPartialJobSkillList<
	JobSkillID.THUNDER_MAGIC_THUNDERBOLT|
	JobSkillID.THUNDER_MAGIC_SHOCK|
	JobSkillID.THUNDER_MAGIC_THUNDERSTORM|
	JobSkillID.THUNDER_MAGIC_THUNDER_AURA
>;

export type IMartialArtsJobSkillList = IPartialJobSkillList<JobSkillID.MARTIAL_ARTS_NONE>;
export type IMysticArtsJobSkillList = IPartialJobSkillList<JobSkillID.MYSTIC_ART_NONE>;
export type IPerformanceJobSkillList = IPartialJobSkillList<JobSkillID.PERFORMANCE_NONE>;
export type IProgramJobSkillList = IPartialJobSkillList<JobSkillID.PROGRAM_NONE>;

export type IPsychokinesisJobSkillList = IPartialJobSkillList<
	JobSkillID.PSYCHOKINESIS_KINETIC_STRIKE|
	JobSkillID.PSYCHOKINESIS_FORGET|
	JobSkillID.PSYCHOKINESIS_PSYCHODOME
>;

export type ISupremacyJobSkillList = IPartialJobSkillList<JobSkillID.SUPREMACY_NONE>;
export type ITrackingJobSkillList = IPartialJobSkillList<JobSkillID.TRACKING_NONE>;
export type IVampirismJobSkillList = IPartialJobSkillList<JobSkillID.VAMPIRISM_NONE>;
export type IWeaponMasteryJobSkillList = IPartialJobSkillList<JobSkillID.WEAPON_MASTERY_NONE>;
