export type PsychokinesisSkillID = 'PSYCHOKINESIS_KINETIC_STRIKE' | 'PSYCHOKINESIS_CONFUSION' | 'PSYCHOKINESIS_PSYCHODOME';
export type WhiteMagicSkillID = 'WHITE_MAGIC_HEAL' | 'WHITE_MAGIC_REMEDY' | 'WHITE_MAGIC_REGENERATE' | 'WHITE_MAGIC_GROUP_HEAL' | 'WHITE_MAGIC_HOLY_AURA' | 'WHITE_MAGIC_REVIVE';
export type BlackMagicSkillID = 'BLACK_MAGIC_DARK_AURA';
export type FireMagicSkillID = 'FIRE_MAGIC_FIREBALL' | 'FIRE_MAGIC_BURN' | 'FIRE_MAGIC_FIRESTORM' | 'FIRE_MAGIC_FIRE_AURA';
export type WaterMagicSkillID = 'WATER_MAGIC_SPLASH' | 'WATER_MAGIC_SILENCE' | 'WATER_MAGIC_FLOOD' | 'WATER_MAGIC_WATER_AURA';
export type WindMagicSkillID = 'WIND_MAGIC_AIR_BLAST' | 'WIND_MAGIC_JET_STREAM' | 'WIND_MAGIC_TORNADO' | 'WIND_MAGIC_WIND_AURA';
export type EarthMagicSkillID = 'EARTH_MAGIC_BOULDER' | 'EARTH_MAGIC_EARTH_SPIKE' | 'EARTH_MAGIC_EARTHQUAKE' | 'EARTH_MAGIC_STONE_SKIN';
export type IceMagicSkillID = 'ICE_MAGIC_ICE_SPEAR' | 'ICE_MAGIC_FREEZE' | 'ICE_MAGIC_BLIZZARD' | 'ICE_MAGIC_FROST_AURA';
export type ThunderMagicSkillID = 'THUNDER_MAGIC_THUNDERBOLT' | 'THUNDER_MAGIC_SHOCK' | 'THUNDER_MAGIC_THUNDERSTORM' | 'THUNDER_MAGIC_THUNDER_AURA';

export type MagicSkillID =
	PsychokinesisSkillID |
	WhiteMagicSkillID | BlackMagicSkillID |
	FireMagicSkillID | WaterMagicSkillID |
	WindMagicSkillID | EarthMagicSkillID |
	IceMagicSkillID | ThunderMagicSkillID;
